### ISSUE TITLE
Calculation of Topographic wetness index based on TAGEE

### ISSUE THREAD

**Issue by WURXPP** [zecojls/tagee#1]
Hi Lucas,

Thanks for developing such a fantastic tool! I would like to know is it possible to calculate the Topographic Wetness Index and the Topographic Position Index in GEE based on the tool you developed?

Thanks! Looking forward to hearing from you.

**Comment by zecojls** [comment]
Dear @WURXPP, glad to hear that from you! Yep, TWI and TPI are extremely important for environmental mapping and modelling. During the time I was developing the tool, I was unable to include them because estimating non-local variables (such as specific catchment area, which depends not only on a moving window but on the catchment area, stream network etc.) is resource-intensive. Idk how things are now or if they implemented the recursive processing in GEE (i.e. input depends on previous output and so on) for calculating these attributes. So I'm sorry but we are still unable to calculate TWI and TPI with TAGEE :/

**Comment by WURXPP** [comment]
> Dear @WURXPP, glad to hear that from you! Yep, TWI and TPI are extremely important for environmental mapping and modelling. During the time I was developing the tool, I was unable to include them because estimating non-local variables (such as specific catchment area, which depends not only on a moving window but on the catchment area, stream network etc.) is resource-intensive. Idk how things are now or if they implemented the recursive processing in GEE (i.e. input depends on previous output and so on) for calculating these attributes. So I'm sorry but we are still unable to calculate TWI and TPI with TAGEE :/

Dear Lucas,
Thanks for such a quick response! Indeed, like what you said calculating the catchment area and stream network is resource-intensive. Despite that, the TAGEE tool is still very useful. I will look for some other solutions (e.g., using external software like SAGA GIS) to calculate the TWI and TPI.
Kind regards.

**Comment by zecojls** [comment]
Nice! Another option is [Whitebox](https://jblindsay.github.io/ghrg/Whitebox/). Either way, both SAGA and Whitebox have a good GUI for small-scale projects or can be explored with a programming interface in challenging projects. Best
